services:
  mongo:
    image: mongo:7.0
    container_name: todo-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: todo
    volumes:
      - mongo_data:/data/db
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: todo-keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    ports:
      - "8080:8080"
    command: start-dev
volumes:
  mongo_data:
